### ISSUE TITLE
Timeout on /items

### ISSUE THREAD

**Issue by alukach** [developmentseed/sat-api-pg#20]
When performing a `GET` request on the `/items` endpoint, a `504 Gateway Timeout` response is returned.

My guess is that the endpoint is not paginating by default and is attempting to return the 80k records in my `items` table, however I have not yet looked into the codebase to verify that this is true.

**Comment by sharkinsspatial** [comment]
@alukach Default pagination is included in https://github.com/developmentseed/sat-api-pg/commit/1b5803ba8d466afb04e4315489d37b9437f66555.  You'll need to update the OpenResty image used in your stack.
